name: "test"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        postgresVersion: ["13", "14"]
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit-openresty"]

    env:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: 127.0.0.1
      DOCKER_POSTGRES_VERSION: ${{ matrix.postgresVersion }}

    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@master

    - name: dependencies
      run: |
        luarocks install busted
        luarocks install luasocket
        luarocks install luasec
        luarocks install moonscript
        luarocks install https://raw.githubusercontent.com/leafo/lua-cjson/master/lua-cjson-dev-1.rockspec
        luarocks install luaossl
        luarocks install cqueues
        [[ "${{ matrix.luaVersion }}" =~ ^5\.[12]$ ]] && luarocks install luabitop || true

    - name: build
      run: |
        luarocks make

    - name: test
      run: |
        busted -o utfTerminal



  test_resty:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        postgresVersion: ["14"]

    env:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: 127.0.0.1
      DOCKER_POSTGRES_VERSION: ${{ matrix.postgresVersion }}

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-openresty@main
      with:
        openrestyVersion: "1.19.9.1"

    - uses: leafo/gh-actions-luarocks@master
      with:
        withLuaPath: "/usr/local/openresty/luajit/"

    - name: dependencies
      run: |
        luarocks install busted
        luarocks install moonscript
        luarocks install https://raw.githubusercontent.com/leafo/lua-cjson/master/lua-cjson-dev-1.rockspec
        luarocks install lua-resty-openssl

    - name: build
      run: |
        luarocks make

    - name: test
      run: |
        resty spec/resty_busted.lua




  test_redbean:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        postgresVersion: ["13"]
        luaVersion: ["5.4"]

    env:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: 127.0.0.1
      DOCKER_POSTGRES_VERSION: ${{ matrix.postgresVersion }}

    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@master

    - name: dependencies
      run: |
        luarocks install moonscript --dev
        luarocks install busted
        luarocks path

    - name: build
      run: |
        #luarocks make
        moonc spec
        mkdir redbean-pgmoon

    - name: Clone Propagram/pgmoon
      uses: actions/checkout@master
      with:
        repository: Propagram/pgmoon
        path: redbean-pgmoon/pgmoon

    - name: install
      working-directory: redbean-pgmoon
      run: |
        sudo apt install zip curl
        curl https://redbean.dev/redbean-latest.com >redbean.com
        chmod +x redbean.com
        sh ./redbean.com --assimilate
        moonc pgmoon
        mv pgmoon .lua
        zip -r redbean.com .lua
        rm -r .lua
        mv /home/runner/work/pgmoon/pgmoon/.luarocks/share/lua/5.4 .lua
        zip -u -r redbean.com .lua
        rm -r .lua
        mv /home/runner/work/pgmoon/pgmoon/.luarocks/lib/lua/5.4 .lua
        zip -u -r redbean.com .lua

    - name: test
      working-directory: redbean-pgmoon
      run: |
        ./redbean.com -i ../spec/pgmoon_spec.lua

